language: R
dist: xenial 
cache: packages
sudo: true

before_install:
  - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev unixodbc-dev
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - export MLJAR_TOKEN=example
  
  
r_github_packages:
  - ModelOriented/DALEX
  - rstudio/reticulate
  - r-lib/covr
    
env:
  global:
  - R_CHECK_ARGS="--timings"

notifications:
  email: false



after_success:
- Rscript -e 'library(covr); codecov()'
